# Build master commits
trigger:
  batch: false
  branches:
    include:
      - daml

# Enable PR triggers that target the master branch
pr:
  autoCancel: true # cancel previous builds on push
  branches:
    include:
      - daml

jobs:
  - template: ./.azure/linux-stack.yml
  - template: ./.azure/windows-stack.yml
