# Build master commits
trigger:
  batch: false
  branches:
    include:
      - daml

# Enable PR triggers that target the master branch
pr:
  autoCancel: true # cancel previous builds on push
  branches:
    include:
      - daml

jobs:
  - job: run
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - bash: |
        set -euo pipefail

        echo "All good!"
